# Generated by Django 4.2.9 on 2024-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_telegramanalysis_measure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.DeleteModel(
            name='TelegramAnalysis',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='api_key',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
