# Generated by Django 4.2.9 on 2024-04-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_delete_analysisresult_delete_telegramanalysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='api_key',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
